/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package brain.view;

import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.util.Timer;
import java.util.TimerTask;

/**
 *
 */
public class panel_fastmath1 extends javax.swing.JFrame {
//        sys_Game game = new sys_Game();
        sys_fastmath g_fm = new sys_fastmath();
        Random rand = new Random();
        
    
    /**
     * Creates new 
     */
//        int jawaban = g_fm.getAnswer();
        int score = 0;
        int userAnswer;          
        
        //Variable Membuat Waktu;
        int waktu = 5;
    
        
    private void hapus(){
        this.dispose();
    }    
    static Timer timer;    
    public panel_fastmath1() {
        initComponents();
        lbsoal3.setText(g_fm.setQuestion());
        lbscore.setText(Integer.toString(score));
        
        //Membuat Timer
        int delay = 1000;
        int period = 1000;
        timer = new Timer();
        timer.schedule(new TimerTask() {
            @Override
            public void run(){
               lbTimer.setText(Integer.toString(waktu));
               waktu--;
                if (waktu == -1) {
                    timer.cancel();
                    new panel_timout().show();
                    hapus();
                } 
            }
        }, delay, period);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbFastmath = new javax.swing.JLabel();
        lbFastmath4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbTimer = new javax.swing.JLabel();
        lbjudul1 = new javax.swing.JLabel();
        lbscore = new javax.swing.JLabel();
        lbjudul2 = new javax.swing.JLabel();
        lbsoal3 = new javax.swing.JLabel();
        lbjudul3 = new javax.swing.JLabel();
        lbresponse = new javax.swing.JLabel();
        jTxuser = new javax.swing.JTextField();
        lbjudul5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SERVICE'S");
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setMaximumSize(new java.awt.Dimension(350, 265));
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 460, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/service/icon/creative-idea.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("UniSansBold", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("-");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, -1, 30));

        jLabel5.setFont(new java.awt.Font("UniSansBold", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("X");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, -1, 30));

        lbFastmath.setFont(new java.awt.Font("Uni Sans  ", 1, 36)); // NOI18N
        lbFastmath.setForeground(new java.awt.Color(255, 255, 255));
        lbFastmath.setIcon(new javax.swing.ImageIcon(getClass().getResource("/service/icon/abacus.png"))); // NOI18N
        lbFastmath.setToolTipText("");
        lbFastmath.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lbFastmath.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbFastmathMouseClicked(evt);
            }
        });
        jPanel2.add(lbFastmath, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 650, 100, 110));

        lbFastmath4.setFont(new java.awt.Font("UniSansBold", 1, 36)); // NOI18N
        lbFastmath4.setForeground(new java.awt.Color(255, 255, 255));
        lbFastmath4.setText("Fast Math");
        lbFastmath4.setToolTipText("");
        lbFastmath4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(lbFastmath4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 750, -1, 30));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 610, 10));

        lbTimer.setFont(new java.awt.Font("UniSansBold", 1, 36)); // NOI18N
        lbTimer.setForeground(new java.awt.Color(255, 255, 255));
        lbTimer.setToolTipText("");
        jPanel2.add(lbTimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 90, 50));

        lbjudul1.setFont(new java.awt.Font("Uni Sans  ", 1, 65)); // NOI18N
        lbjudul1.setForeground(new java.awt.Color(255, 255, 255));
        lbjudul1.setText("BRAIN");
        lbjudul1.setToolTipText("");
        jPanel2.add(lbjudul1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 210, 80));

        lbscore.setFont(new java.awt.Font("UniSansBold", 1, 36)); // NOI18N
        lbscore.setForeground(new java.awt.Color(255, 255, 255));
        lbscore.setToolTipText("");
        jPanel2.add(lbscore, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, 90, 50));

        lbjudul2.setFont(new java.awt.Font("Uni Sans  ", 1, 65)); // NOI18N
        lbjudul2.setForeground(new java.awt.Color(255, 255, 255));
        lbjudul2.setText("TRAIN");
        lbjudul2.setToolTipText("");
        jPanel2.add(lbjudul2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 210, 80));

        lbsoal3.setFont(new java.awt.Font("UniSansBold", 1, 60)); // NOI18N
        lbsoal3.setForeground(new java.awt.Color(255, 255, 255));
        //String soal = g_fm.setQuestion();
        //int jawaban = g_fm.getAnswer();
        lbsoal3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        //btnpilihan1.setText(Integer.toString(jawaban));
        //btnpilihan2.setText(Integer.toString(rand.nextInt(11)));
        //btnpilihan3.setText(Integer.toString(rand.nextInt(12)));
        //btnpilihan4.setText(Integer.toString(rand.nextInt(13)));
        lbsoal3.setToolTipText("");
        jPanel2.add(lbsoal3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 270, 80));

        lbjudul3.setFont(new java.awt.Font("UniSansBold", 1, 36)); // NOI18N
        lbjudul3.setForeground(new java.awt.Color(255, 255, 255));
        lbjudul3.setText("Timer :");
        lbjudul3.setToolTipText("");
        jPanel2.add(lbjudul3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 110, 50));

        lbresponse.setFont(new java.awt.Font("UniSansBold", 1, 36)); // NOI18N
        lbresponse.setForeground(new java.awt.Color(255, 255, 255));
        lbresponse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbresponse.setToolTipText("");
        jPanel2.add(lbresponse, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 530, 230, 50));

        jTxuser.setFont(new java.awt.Font("Uni Sans Heavy CAPS", 0, 36)); // NOI18N
        jTxuser.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxuserActionPerformed(evt);
            }
        });
        jTxuser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxuserKeyPressed(evt);
            }
        });
        jPanel2.add(jTxuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 230, 130));

        lbjudul5.setFont(new java.awt.Font("UniSansBold", 1, 36)); // NOI18N
        lbjudul5.setForeground(new java.awt.Color(255, 255, 255));
        lbjudul5.setText("Score : ");
        lbjudul5.setToolTipText("");
        jPanel2.add(lbjudul5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 110, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void lbFastmathMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbFastmathMouseClicked

    }//GEN-LAST:event_lbFastmathMouseClicked

    private void jTxuserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxuserKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxuserKeyPressed

    private void jTxuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxuserActionPerformed
        // TODO add your handling code here:
        if(Integer.parseInt(jTxuser.getText()) == g_fm.getAnswer()){
            score++;
            waktu = 5;
            lbscore.setText(Integer.toString(score));
            lbresponse.setForeground(Color.green);
            lbresponse.setText("CORRECT!");
        } else if (Integer.parseInt(jTxuser.getText()) != g_fm.getAnswer()) {
            score = 0;
            lbscore.setText(Integer.toString(score));
            lbresponse.setForeground(Color.red);
            lbresponse.setText("INCORRECT!");
        }
        lbsoal3.setText(""+g_fm.setQuestion());
        jTxuser.setText(null);
    }//GEN-LAST:event_jTxuserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(panel_fastmath1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(panel_fastmath1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(panel_fastmath1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(panel_fastmath1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new panel_fastmath1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTxuser;
    private javax.swing.JLabel lbFastmath;
    private javax.swing.JLabel lbFastmath4;
    private javax.swing.JLabel lbTimer;
    private javax.swing.JLabel lbjudul1;
    private javax.swing.JLabel lbjudul2;
    private javax.swing.JLabel lbjudul3;
    private javax.swing.JLabel lbjudul5;
    private javax.swing.JLabel lbresponse;
    private javax.swing.JLabel lbscore;
    private javax.swing.JLabel lbsoal3;
    // End of variables declaration//GEN-END:variables
}
