/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package brain.view;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 */
public class panel_fastmath extends javax.swing.JFrame {
        sys_Game game = new sys_Game();
        sys_fastmath g_fm = new sys_fastmath();
//        eksperimen x = new eksperimen();
        Random rand = new Random();
        
    
    /**
     * Creates new 
     */
        String soal = g_fm.setQuestion();
        int jawaban = g_fm.getAnswer();
        int score = 0;
        
        
        
    public panel_fastmath() {
        initComponents();
        lbsoal3.setText(soal);
        
        ////////////////////////////////////////////
        int size = 4;

        ArrayList<Integer> list = new ArrayList<Integer>(size);
        for(int i = 1; i <= size; i++) {
            list.add(i);
        }

        Random rand = new Random();
//        int index = 0;
        while(list.size() > 0) {
            int index = rand.nextInt(list.size());
//            System.out.println("Selected: "+list.remove(index));
           switch(list.remove(index)){
               case 1 : btnpilihan2.setText(Integer.toString(jawaban));break;
               case 2 : btnpilihan1.setText(Integer.toString(rand.nextInt(11)));break;
               case 3 : btnpilihan4.setText(Integer.toString(rand.nextInt(12)));;break;
               case 4 : btnpilihan3.setText(Integer.toString(rand.nextInt(13)));;break;
           }
        }
        
        
        ///////////////////////////////////////////
//        btnpilihan1.setText(Integer.toString(jawaban));
//        btnpilihan2.setText(Integer.toString(rand.nextInt(11)));
//        btnpilihan3.setText(Integer.toString(rand.nextInt(12)));
//        btnpilihan4.setText(Integer.toString(rand.nextInt(13)));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();
        btnpilihan1 = new javax.swing.JButton();
        btnpilihan3 = new javax.swing.JButton();
        btnpilihan2 = new javax.swing.JButton();
        lbFastmath = new javax.swing.JLabel();
        lbFastmath4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbscore = new javax.swing.JLabel();
        lbjudul1 = new javax.swing.JLabel();
        lbjudul2 = new javax.swing.JLabel();
        lbsoal3 = new javax.swing.JLabel();
        btnpilihan4 = new javax.swing.JButton();
        lbjudul3 = new javax.swing.JLabel();
        lbjudul4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SERVICE'S");
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setMaximumSize(new java.awt.Dimension(350, 265));
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 460, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/service/icon/creative-idea.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("UniSansBold", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("-");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, -1, 30));

        jLabel5.setFont(new java.awt.Font("UniSansBold", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("X");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, -1, 30));

        btnRefresh.setBackground(new java.awt.Color(204, 0, 0));
        btnRefresh.setFont(new java.awt.Font("Uni Sans Heavy CAPS", 1, 18)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnRefresh.setText("Restart");
        btnRefresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        jPanel2.add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 740, 140, 40));

        btnpilihan1.setBackground(new java.awt.Color(41, 128, 185));
        btnpilihan1.setFont(new java.awt.Font("Uni Sans Heavy CAPS", 1, 36)); // NOI18N
        btnpilihan1.setForeground(new java.awt.Color(255, 255, 255));
        btnpilihan1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnpilihan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpilihan1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnpilihan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 220, 130));

        btnpilihan3.setBackground(new java.awt.Color(41, 128, 185));
        btnpilihan3.setFont(new java.awt.Font("Uni Sans Heavy CAPS", 1, 36)); // NOI18N
        btnpilihan3.setForeground(new java.awt.Color(255, 255, 255));
        btnpilihan3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnpilihan3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpilihan3ActionPerformed(evt);
            }
        });
        jPanel2.add(btnpilihan3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 220, 130));

        btnpilihan2.setBackground(new java.awt.Color(41, 128, 185));
        btnpilihan2.setFont(new java.awt.Font("Uni Sans Heavy CAPS", 1, 36)); // NOI18N
        btnpilihan2.setForeground(new java.awt.Color(255, 255, 255));
        btnpilihan2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnpilihan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpilihan2ActionPerformed(evt);
            }
        });
        jPanel2.add(btnpilihan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 520, 220, 130));

        lbFastmath.setFont(new java.awt.Font("Uni Sans  ", 1, 36)); // NOI18N
        lbFastmath.setForeground(new java.awt.Color(255, 255, 255));
        lbFastmath.setIcon(new javax.swing.ImageIcon(getClass().getResource("/service/icon/abacus.png"))); // NOI18N
        lbFastmath.setToolTipText("");
        lbFastmath.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lbFastmath.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbFastmathMouseClicked(evt);
            }
        });
        jPanel2.add(lbFastmath, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 650, 100, 110));

        lbFastmath4.setFont(new java.awt.Font("UniSansBold", 1, 36)); // NOI18N
        lbFastmath4.setForeground(new java.awt.Color(255, 255, 255));
        lbFastmath4.setText("Fast Math");
        lbFastmath4.setToolTipText("");
        lbFastmath4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(lbFastmath4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 750, -1, 30));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 610, 10));

        lbscore.setFont(new java.awt.Font("UniSansBold", 1, 36)); // NOI18N
        lbscore.setForeground(new java.awt.Color(255, 255, 255));
        lbscore.setToolTipText("");
        jPanel2.add(lbscore, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, 90, 50));

        lbjudul1.setFont(new java.awt.Font("Uni Sans  ", 1, 65)); // NOI18N
        lbjudul1.setForeground(new java.awt.Color(255, 255, 255));
        lbjudul1.setText("BRAIN");
        lbjudul1.setToolTipText("");
        jPanel2.add(lbjudul1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 210, 80));

        lbjudul2.setFont(new java.awt.Font("Uni Sans  ", 1, 65)); // NOI18N
        lbjudul2.setForeground(new java.awt.Color(255, 255, 255));
        lbjudul2.setText("TRAIN");
        lbjudul2.setToolTipText("");
        jPanel2.add(lbjudul2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 210, 80));

        lbsoal3.setFont(new java.awt.Font("UniSansBold", 1, 60)); // NOI18N
        lbsoal3.setForeground(new java.awt.Color(255, 255, 255));
        //String soal = g_fm.setQuestion();
        //int jawaban = g_fm.getAnswer();
        //btnpilihan1.setText(Integer.toString(jawaban));
        //btnpilihan2.setText(Integer.toString(rand.nextInt(11)));
        //btnpilihan3.setText(Integer.toString(rand.nextInt(12)));
        //btnpilihan4.setText(Integer.toString(rand.nextInt(13)));
        lbsoal3.setToolTipText("");
        jPanel2.add(lbsoal3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 310, 80));

        btnpilihan4.setBackground(new java.awt.Color(41, 128, 185));
        btnpilihan4.setFont(new java.awt.Font("Uni Sans Heavy CAPS", 1, 36)); // NOI18N
        btnpilihan4.setForeground(new java.awt.Color(255, 255, 255));
        btnpilihan4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnpilihan4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpilihan4ActionPerformed(evt);
            }
        });
        jPanel2.add(btnpilihan4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 520, 220, 130));

        lbjudul3.setFont(new java.awt.Font("UniSansBold", 1, 36)); // NOI18N
        lbjudul3.setForeground(new java.awt.Color(255, 255, 255));
        lbjudul3.setText("Timer");
        lbjudul3.setToolTipText("");
        jPanel2.add(lbjudul3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 110, 50));

        lbjudul4.setFont(new java.awt.Font("UniSansBold", 1, 36)); // NOI18N
        lbjudul4.setForeground(new java.awt.Color(255, 255, 255));
        lbjudul4.setText("Score : ");
        lbjudul4.setToolTipText("");
        jPanel2.add(lbjudul4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 110, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void lbFastmathMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbFastmathMouseClicked

    }//GEN-LAST:event_lbFastmathMouseClicked

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:        
        new panel_fastmath().show();
        this.dispose();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnpilihan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpilihan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnpilihan1ActionPerformed

    private void btnpilihan3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpilihan3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnpilihan3ActionPerformed

    private void btnpilihan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpilihan2ActionPerformed
        // TODO add your handling code here:
            new panel_fastmath().show();
            score += 1;
            lbscore.setText(Integer.toString(score));
            lbsoal3.setText(soal);
            
//            this.dispose();
            
    }//GEN-LAST:event_btnpilihan2ActionPerformed

    private void btnpilihan4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpilihan4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnpilihan4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(panel_fastmath.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(panel_fastmath.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(panel_fastmath.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(panel_fastmath.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new panel_fastmath().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnpilihan1;
    private javax.swing.JButton btnpilihan2;
    private javax.swing.JButton btnpilihan3;
    private javax.swing.JButton btnpilihan4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbFastmath;
    private javax.swing.JLabel lbFastmath4;
    private javax.swing.JLabel lbjudul1;
    private javax.swing.JLabel lbjudul2;
    private javax.swing.JLabel lbjudul3;
    private javax.swing.JLabel lbjudul4;
    private javax.swing.JLabel lbscore;
    private javax.swing.JLabel lbsoal3;
    // End of variables declaration//GEN-END:variables
}
